apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xyztech-web-app
  name: xyztech-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyztech-web-app
  template:
    metadata:
      labels:
        app: xyztech-web-app
    spec:
      containers:
      - image: karthickmuthaiyan/xyztech-webapp-docker-image
        name: xyztech-webapp-docker-image
