apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-web-app
  name: sample-web-app-lb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-web-app
  type: LoadBalancer
